# Generated by Django 6.0.5 on 2026-05-17 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='detail',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
